[package]
name = "recap-ng-derive"
version = "0.0.0-a.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lib]
proc-macro = true

[dependencies]
darling = "0.23.0"
indexmap = "2.14.0"
proc-macro2 = "1.0.106"
quote = "1.0.45"
regex-syntax = "0.8.10"
syn = "2.0.117"

[features]
schemars = []
